FROM python:3.11

# Install any dependencies
RUN pip install --upgrade pip

# Set the working directory in the container
WORKDIR /workspace

# Copy the current directory contents into the container at /workspace
ADD . /workspace
